// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("API.Entities.Senario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Particulate_Matter_Predicted_AQI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient_Age")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient_Allergies")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient_Co_Morbidities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patient_Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Risk_Level_Target_Area_Code")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Senarios");
                });
#pragma warning restore 612, 618
        }
    }
}
